### PR TITLE
Message update

### PR DESCRIPTION
**Pull request by vlad-lukyanov**
Add message editing ( #39 )

### CODE REVIEW

**Comment by beevee** [comment]
Hi guys! Is this going to be merged anytime soon?

**Comment by vlad-lukyanov** [comment]
@beevee as this breaks api I think this will be merged in v2 only, or never

**Comment by beevee** [comment]
May I ask, why did you omit `ParseMode` configuration in message edits?

**Comment by vlad-lukyanov** [comment]
@beevee my bug, fixed

**Comment by tucnak** [comment]
I'd like to merge this in ASAP. Let's figure out how we should handle it.

**Comment by tucnak** [comment]
Closing this in favor of v2 API

**Pull request closed without merging**
