### PR TITLE
Add silent messages option for sending messages/files

### PR DESCRIPTION
**Pull request by toby3d**
Quick explain: https://telegram.org/blog/channels-2-0#silent-messages

### CODE REVIEW

**Comment by tucnak** [comment]
I don't like how DisableNotification is duplicated around all the structs, makes them look bloat. It also misses some documentation. "Disable notification" sounds really ambigious: what notification? disable how? where? and so on.

**Comment by toby3d** [comment]
@tucnak fixed. Check, please. ^_^
P.S.: "DisableNotification" is official parameter name in BotAPI docs (like [here](https://core.telegram.org/bots/api#sendmessage)).

**Comment by tucnak** [comment]
Looks much better!

**Comment by toby3d** [comment]
Yaay! Thanks! ^_^

**Pull request merged**
