### PR TITLE
fixed wrong method name

### PR DESCRIPTION
**Pull request by anna-oake**

### CODE REVIEW

**Review by irgendwr — APPROVED** [review]

**Comment by stek29** [comment]
Please rebase on top of latest `v2`, issue causing CI build failure was fixed.

**Comment by anna-oake** [comment]
@stek29 do we really need CI build check for such a small and obvious change?

**Comment by stek29** [comment]
@aprosvetova GitHub usually won't let you merge PR without CI build check passing

**Comment by tucnak** [comment]
Soz for taking so long with the request.

**Pull request merged**
