### PR TITLE
add implementation for a webhook poller

### PR DESCRIPTION
**Pull request by ulrichSchreiner**
Hi,

this PR implements the `Poller` interface with a webhook backend. I need this to run a telebot in a kubernetes cluster behind a loadbalancer with multiple instances. With this implementation you can start telebot which listens on a local interface and also configure an endpoint which can be a loadbalancer or reverseproxy.

if you have `ngrok` installed, you can do a `ngrok http 8000` and you will get a public available URL with a legal certificate. than you can start a bot listening on `localhost:8000` with the public URL from ngrok:

~~~
b, err := tb.NewBot(tb.Settings{
	Token: "my-bot-token",
	Poller: &tb.Webhook{
		Listen: "127.0.0.1:8000",
		Endpoint: &tb.WebhookEndpoint{
			PublicURL: "https://abc123123ab.ngrok.io",
		},
	},
})
~~~
If you want selfsigned certificates, you can specifiy them with the `WebhookTLS` configuration. Please be aware that it seems that telegram at least checks the domain in the certificate.

### CODE REVIEW

**Comment by tucnak** [comment]
Great work! I never would've thought anyone would actually be down to implement it. Updating README in a while...

Cheers!

**Comment by ulrichSchreiner** [comment]
thx for merging!

my last commit allowed custom muxes to, so the upper example can also be written as:
~~~
p := &tb.Webhook{
  Endpoint: &tb.WebhookEndpoint{
    PublicURL: "https://abc123123ab.ngrok.io",
  },
}

b, err := tb.NewBot(tb.Settings{
  Token: "my-bot-token",
  Poller: p,
})

...
http.Serve("/tg", p)
~~~
so one can have a custom http mux. i'm using this in my kubernetes cluster, it works really great :-)

**Comment by tucnak** [comment]
Hey it's pretty cool! Do you run it inside GKE or somewhere else? I'm slowly getting into the whole cloud thing. I found Go over GAE in Standard to be incredibly effective and cheap. It also has direct access to things like sql, storage, memcached etc. out of the box. See https://github.com/tucnak/levi

**Comment by tucnak** [comment]
Production instance with a couple endpoints and DB access is a 2 MB binary, consuming something like 12 MB of memory and it scales very, very well. Considering you can get it up and running in what, 5 minutes? I haven't seen a single thing more resourceful than that in my whole life. Also, looking forward to what Google is gonna do with cloud functionsl, as they are currently lagging behind AWS heavily.

**Comment by ulrichSchreiner** [comment]
we have a custom kube cluster with digitalocean. old version of our system used the app engine. it was great, until our traffic an data requirments increased more and more. than we came to the point that dedicated machines are cheaper than the appengine.

**Comment by KROSF** [comment]
> thx for merging!
> 
> my last commit allowed custom muxes to, so the upper example can also be written as:
> 
> ```
> p := &tb.Webhook{
>   Endpoint: &tb.WebhookEndpoint{
>     PublicURL: "https://abc123123ab.ngrok.io",
>   },
> }
> 
> b, err := tb.NewBot(tb.Settings{
>   Token: "my-bot-token",
>   Poller: p,
> })
> 
> ...
> http.Serve("/tg", p)
> ```
> 
> so one can have a custom http mux. i'm using this in my kubernetes cluster, it works really great :-)

How you start the bot?

**Comment by ulrichSchreiner** [comment]
You do not have to *start* it. As long as your token is valid and the given `PublicURL` is accessible from the internet (no localhost or any other private address) it simply works.

**Pull request merged**
