### PR TITLE
Add Chat type to types.go

### PR DESCRIPTION
**Pull request by aladine**
https://core.telegram.org/bots/api#recent-changes

### CODE REVIEW

**Comment by tucnak** [comment]
You'd also need to tweak docs of User (it doesn't fit "or group chat", iirc), merge it with #18 and gofmt, please

**Comment by aladine** [comment]
Okie, I will update you soon. Branch: aladine:patch-3

**Comment by aladine** [comment]
You can proceed to merge my pull request

**Comment by tucnak** [comment]
Seems amazing, yet another little nitpick. Can you please squash it (my inner perfectionist is crying on this github merges)?

**Comment by aladine** [comment]
After I run go test, there are some error. I will close this and open another pull request

**Pull request closed without merging**
