### PR TITLE
ref: set omitemty for InlineQueryChat to avoid telegram api limits

### PR DESCRIPTION
**Pull request by naderAbolfazli**

### CODE REVIEW

**Comment by demget** [comment]
It breaks backwards compatibility, because you won't be able to answer inline query with empty  `switch_inline_query_current_chat` param

**Comment by demget** [comment]
Can you elaborate please, what limits are you talking about?

**Comment by naderAbolfazli** [comment]
> Can you elaborate please, what limits are you talking about?
I get it. my problem was using another bot server instead of telegram that not handles this param.

**Comment by stek29** [comment]
@naderAbolfazli are there other servers for BotAPI?

**Comment by naderAbolfazli** [comment]
> @naderAbolfazli are there other servers for BotAPI?

yes. in other messengers

**Pull request closed without merging**
