### PR TITLE
Update message, user, chat types following telegram api changes 

### PR DESCRIPTION
**Pull request by aladine**
Updates on 8 Oct
User and Chat are separate objects in Message object. 

https://core.telegram.org/bots/api#recent-changes

### CODE REVIEW

**Comment by tucnak** [comment]
Rebase for current master, it has appropriate API key. Once Travis succeeds, do a squash please.

**Comment by aladine** [comment]
How do I set API SECRET key in Travis. I can set in my computer but Travis is cloud platform

**Comment by aladine** [comment]
Okie, it passed now. I change TELEBOT_SECRET to TELEGRAM_SECRET in the test.

**Comment by tucnak** [comment]
Change it back to `TELEBOT_SECRET` please, it's the correct one.

**Comment by aladine** [comment]
Okie, done

**Comment by tucnak** [comment]
Done.

**Pull request closed without merging**
