### PR TITLE
update KeyboardButtonRequestUsers 	KeyboardButtonRequestChat api 

### PR DESCRIPTION
**Pull request by yaooort**
new Api 
```
RequestName     *bool `json:"request_name,omitempty"`     // user, optional
RequestTitle    *bool `json:"request_title,omitempty"`    // chat, optional
RequestUsername *bool `json:"request_username,omitempty"` // chat & user, optional
RequestPhoto    *bool `json:"request_photo,omitempty"`    // chat & user, optional
```

### CODE REVIEW

**Comment by yaooort** [comment]
close #674

**Comment by kyrylo** [comment]
Thanks for the PR, @yaooort!

@tucnak, can we please get this merged?

**Comment by kyrylo** [comment]
Hey @demget! May I know why this was closed?

**Comment by demget** [comment]
@kyrylo already implemented in other PR

**Pull request closed without merging**
